#!/usr/bin/env python3
"""Axiom guards for LeanSphincs (writes LeanSphincs/Axioms.lean).

From formal/sphincs:
    lake env lean scripts/SphincsTheorems.lean            # writes sphincs_theorems.txt
    python3 scripts/sphincs_axioms.py prepare             # writes .build/sphincs_print_axioms.lean
    lake env lean .build/sphincs_print_axioms.lean > .build/sphincs_axioms_out.txt
    python3 scripts/sphincs_axioms.py emit                # writes LeanSphincs/Axioms.lean
Every public theorem of every LeanSphincs module gets a #guard_msgs
guard with the exact output of #print axioms; `emit` refuses any axiom other than propext,
Classical.choice and Quot.sound.
"""
import os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ALLOWED = {'propext', 'Classical.choice', 'Quot.sound'}
EXTRA_IMPORTS = ['LeanSphincs.' + f[:-5] for f in sorted(os.listdir(os.path.join(ROOT, 'LeanSphincs')))
                 if f.endswith('.lean') and f != 'Axioms.lean']

def read_list():
    rows = []
    for line in open(os.path.join(ROOT, 'sphincs_theorems.txt')):
        line = line.strip()
        if not line:
            continue
        mod, name = line.split(' ', 1)
        if mod == 'LeanSphincs.Axioms':
            continue
        rows.append((mod, name))
    return rows

def prepare():
    rows = read_list()
    os.makedirs(os.path.join(ROOT, '.build'), exist_ok=True)
    mods = sorted(set(m for m, _ in rows) | set(EXTRA_IMPORTS))
    with open(os.path.join(ROOT, '.build', 'sphincs_print_axioms.lean'), 'w') as f:
        for m in mods:
            f.write('import %s\n' % m)
        f.write('\n')
        for _, n in rows:
            f.write('#print axioms %s\n' % n)
    print('%d theorems, %d modules' % (len(rows), len(mods)))

def emit():
    rows = read_list()
    out = open(os.path.join(ROOT, '.build', 'sphincs_axioms_out.txt')).read()
    # one message per theorem, each starting with the quoted name at the beginning of a line
    parts = re.split(r"^(?=')", out, flags=re.M)
    msgs = [p.strip() for p in parts if p.strip()]
    assert len(msgs) == len(rows), (len(msgs), len(rows))
    mods = sorted(set(m for m, _ in rows) | set(EXTRA_IMPORTS))
    lines = []
    for m in mods:
        lines.append('import %s' % m)
    lines.append('')
    lines.append('/-! Axiom guards: every public theorem of `LeanSphincs` depends on a subset of `propext`,')
    lines.append('`Classical.choice` and `Quot.sound` (generated by `scripts/sphincs_axioms.py`). -/')
    lines.append('')
    for (m, n), msg in zip(rows, msgs):
        flat = ' '.join(msg.split())
        mm = re.match(r"'(.*)' depends on axioms: \[(.*)\]$", flat)
        if mm:
            assert mm.group(1) == n, (mm.group(1), n)
            axs = [a.strip() for a in mm.group(2).split(',') if a.strip()]
            bad = [a for a in axs if a not in ALLOWED]
            assert not bad, (n, bad)
        else:
            assert flat == "'%s' does not depend on any axioms" % n, flat
        lines.append('/-- info: %s -/' % flat)
        lines.append('#guard_msgs (whitespace := lax) in')
        lines.append('#print axioms %s' % n)
        lines.append('')
    open(os.path.join(ROOT, 'LeanSphincs', 'Axioms.lean'), 'w').write('\n'.join(lines))
    print('%d guards' % len(rows))

if __name__ == '__main__':
    {'prepare': prepare, 'emit': emit}[sys.argv[1]]()
